version: '3.8'

networks:
  localdb:
    driver: ${APP_NETWORK_DRIVER}

services:
  99techapp:
    platform: ${APP_PLATFORM}
    build:
      context: ./.docker/nodejs
      args:
        - VERSION=${NODE_VERSION}
    volumes:
      - ./source/myapp/src:/usr/src/app/src
      - ./source/myapp/config:/usr/src/app/config
    ports:
      - "3000:3000"
    networks:
      - localdb
